spring.application.name=user-service


#Configurar atributos para mi db
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ecommerce;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Nightfalls.12

# Configuracion de la accion de JPA
spring.jpa.hibernate.ddl-auto=update

# Logs para ver informacion de las queries de JPA (dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true