# Configuración para probar la app de forma local
# Duplicar este archivo y quitarle el .example
# application-local.properties no será trackeado por git y no se sube al repositorio

spring.application.name=user-service

server.port=8080

#Configurar atributos para mi DB Local
spring.datasource.url=${DB_URL_LOCAL}
spring.datasource.username=${DB_USERNAME_LOCAL}
spring.datasource.password=${DB_PASSWORD_LOCAL}

# Configuracion de la accion de JPA
spring.jpa.hibernate.ddl-auto=validate

# Logs para ver informacion de las queries de JPA (dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true